package main

import (
	"encoding/json"
	"fmt"
)

type Likes struct {
	pages string
}
type Name struct {
	Surname string
	likes   []Likes
}

func pringStructs() {
	lkes := []Likes{Likes{pages: "names"}}
	name := Name{Surname: "Ayomide", likes: lkes}

	t, _ := json.Marshal(name)
	fmt.Println(string(t))
}

type Buttons struct {
	Type    string `json:"type"`
	URL     string `json:"url,omitempty"`
	Title   string `json:"title"`
	Payload string `json:"payload,omitempty"`
}

// type DefaultAction struct {
// 	Type               string `json:"type,omitempty"`
// 	URL                string `json:"url,omitempty"`
// 	WebviewHeightRatio string `json:"webview_height_ratio,omitempty"`
// }

type Payload struct {
	TemplateType string     `json:"template_type"`
	Els          []Elements `json:"elements"`
}
type Elements struct {
	Title    string `json:"title"`
	Subt     string `json:"subtitle,omitempty"`
	ImageURL string `json:"image_url"`
	//DefAction DefaultAction `json:"default_action,omitempty"`
	Buttons []Buttons `json:"buttons,omitempty"`
}

type Attachment struct {
	Type string  `json:"type"`
	Payl Payload `json:"payload"`
}
type Recipient struct {
	ID string `json:"id"`
}

type Messages struct {
	Attach Attachment `json:"attachment"`
}

type AutoGenerated struct {
	Rec Recipient `json:"recipient"`
	Mes Messages  `json:"message"`
}

func ddg(userID string) {
	btn := []Buttons{Buttons{Type: "postback", Payload: "goog", Title: "Google"}}
	payl := Payload{
		TemplateType: "generic",
		Els: []Elements{
			Elements{
				Title:    "Google Inc",
				Subt:     "Google Inc. Best search engine!",
				ImageURL: "https://image.shutterstock.com/image-photo/mountain-view-causa-december-29-260nw-630500720.jpg",
				Buttons:  btn,
			},
			Elements{
				Title:    "Amazon Inc",
				Subt:     "Amazon Inc. Buy whatever you want!",
				ImageURL: "https://media.npr.org/assets/img/2018/10/19/img_1330_wide-1e73904f1d0f2b6a4e51e714ef6bf32cd502e6c2.jpg?s=6",
				Buttons:  []Buttons{Buttons{Type: "postback", Payload: "aws", Title: "Amazon"}},
			},
		},
	}

	pnt := AutoGenerated{
		Rec: Recipient{
			ID: userID,
		},
		Mes: Messages{
			Attach: Attachment{
				Type: "template",
				Payl: payl,
			},
		},
	}

	gth, _ := json.Marshal(pnt)
	fmt.Println(string(gth))
	callSendAPI(gth)
}
