package main

import (
	"encoding/json"
	"fmt"
)

type Likes struct {
	pages string
}
type Name struct {
	Surname string
	likes   []Likes
}

func pringStructs() {
	lkes := []Likes{Likes{pages: "names"}}
	name := Name{Surname: "Ayomide", likes: lkes}

	t, _ := json.Marshal(name)
	fmt.Println(string(t))
}

type Buttons struct {
	Type    string `json:"type"`
	URL     string `json:"url,omitempty"`
	Title   string `json:"title"`
	Payload string `json:"payload,omitempty"`
}

type DefaultAction struct {
	Type               string `json:"type"`
	URL                string `json:"url"`
	WebviewHeightRatio string `json:"webview_height_ratio"`
}
type Payload struct {
	TemplateType string     `json:"template_type"`
	Els          []Elements `json:"elements"`
}
type Elements struct {
	Title     string        `json:"title"`
	Subt      string        `json:"subtitle,omitempty"`
	ImageURL  string        `json:"image_url"`
	DefAction DefaultAction `json:"default_action,omitempty"`
	Buttons   []Buttons     `json:"buttons,omitempty"`
}

type Attachment struct {
	Type string  `json:"type"`
	Payl Payload `json:"payload"`
}
type Recipient struct {
	ID string `json:"id"`
}

type Messages struct {
	Attach Attachment `json:"attachment"`
}

type AutoGenerated struct {
	Rec Recipient `json:"recipient"`
	Mes Messages  `json:"messages"`
}

func ddg() {
	btn := &[]Buttons{Buttons{Type: "web_url", URL: "https://google.com", Title: "AdeButton"}}
	payl := Payload{
		Els: []Elements{
			Elements{
				Title:    "Ade Carousel1",
				ImageURL: "https://google.com/image/grills/grills.png",
				Buttons:  *btn,
			},
		},
	}

	pnt := AutoGenerated{
		Rec: Recipient{
			ID: "ajdskjfsjfksf",
		},
		Mes: Messages{
			Attach: Attachment{
				Type: "generic",
				Payl: payl,
			},
		},
	}

	gth, _ := json.Marshal(pnt)
	fmt.Println(string(gth))
}
